# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "root" } %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEVELOPMENT") { "chat_app_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST") { "chat_app_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PRODUCTION") { "chat_app_production" } %>
